### ISSUE TITLE
apps is null despite ForecastleApp resource present

### ISSUE THREAD

**Issue by gargath** [stakater/Forecastle#102]
Hi!

I have deployed `forecastle` pretty much along the lines of the helm chart.
My config looks like this:
```
  config.yaml: |-
    headerBackground: "#3f51b5"
    headerForeground: "#ffffff"
    instanceName: "skr forecastle"
    title: Snyk Management Cluster
    crdEnabled: true
    namespaceSelector:
      any: true
```
I added a single `ForecastleApp` CRD to my cluster:
```
apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: argocd
spec:
  group: Command & Control
  icon: https://argoproj.github.io/static/argo-wheel.23b3ad84.png
  name: ArgoCD
  networkRestricted: false
  url: http://<redacted>
```

This app does not seem to get picked up, though. The only log lines from forecastle `Pods` are:
```
skr/forecastle-f4f54b4b4-6frnz[forecastle]: time="2020-04-01T11:56:46Z" level=info msg="Listening at port 3000" _source="Forecastle/forecastle.go:42"
skr/forecastle-f4f54b4b4-xh9wq[forecastle]: time="2020-04-01T11:56:54Z" level=info msg="Looking for forecastle apps in the following namespaces: []" _source="handlers/appsHandler.go:41"
```

Meanwhile `/api/apps` returns `null`, leading the frontend to just display "Results couldn't be loaded due to an error"

Any idea what I might be missing?

**Comment by rasheedamir** [comment]
Sorry @gargath ! we missed the issue; were you able to fix or not? you are welcome to ask us on slack

**Comment by gargath** [comment]
I did not, I'm afraid. I've parked it for now as I haven't had time to look into it further.
Any pointers would be appreciated, but I'm also happy to reach out on Slack.

Could the problem be that I have *only* got a `ForecastleApp` and no `Ingress` annotations?

**Comment by ChipWolf** [comment]
This is probably because of #105 @gargath @rasheedamir

**Comment by gargath** [comment]
I didn't use `helm`. Never touch the stuff. ;-)
The CRD is present and I have successfully added the above with `kubectl apply`.
It's just not showing up on the landing screen.

**Comment by challett** [comment]
+1 on this except I do use Helm, however the CRD **IS** deployed in my cluster.

Any combination of namespaceSelector results in: "Looking for forecastle apps in the following namespaces: []"

**Comment by ahmedwaleedmalik** [comment]
@gargath @challett try omitting the `instanceName` field. It adds an additional filter for instance name to look for and in your case i am assuming no such instance exists. https://github.com/stakater/Forecastle#running-multiple-instances-of-forecastle

Let me know if this solves your issue.

**Comment by challett** [comment]
Hey @ahmedwaleedmalik thanks for the reply.  In my testing to try to resolve this I did remove instanceName to no avail.

I am setting the following configs: `customApps, namespaceSelector.matchNames, title`.

I've also tried `namespaceSelector.any: true` instead of `matchNames` but I'm seeing that the default is true anyways.

**Comment by ahmedwaleedmalik** [comment]
@challett it would be of great help if you could share the complete deployment files that you are using as is. I'll try that at my end on Monday. Will get it fixed accordingly. 

P.s. share the values if you are using helm chart that

**Comment by challett** [comment]
```
forecastle:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: "v1.0.50"
  namespace: default
  image:
    name: stakater/forecastle
    tag: "v1.0.50"
  deployment:
    replicas: 1
    revisionHistoryLimit: 2
    annotations: {}
  config:
    namespaceSelector:
      matchNames:
      - namespace1
      - namespace2
      - namespace3
    title: Company Dashboard
    customApps:
      - name: "Some Custom App"
        icon: https://logo.svg
        url: https://google.com
        group: Apps
  proxy:
    enabled: false
  openshiftOauthProxy:
    enabled: false
  service:
    annotations: {}
    expose: "false"
  ingress:
    hosts:
    - host: dashboard.internal.url
      paths:
      - /
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/protocol: http
      kubernetes.io/ssl-redirect: "true"
  route:
    enabled: false
    annotations: {}
    additionalLabels: {}
    host: ""
    port:
      targetPort: http
    wildcardPolicy: None
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect

```
