### ISSUE TITLE
Forecaslte page fails to load if CR points to a route that doesn't exist

### ISSUE THREAD

**Issue by usamaahmadkhan** [stakater/Forecastle#125]
**Steps to Recreate:**
Create a CustomResource which refers to a route that doesn't exist
```
apiVersion: forecastle.stakater.com/v1alpha1
kind: ForecastleApp
metadata:
  name: <TEST_NAME>
  namespace: <TEST_NAMESPACE>
spec:
  name: TestRoute
  group: Build
  icon: <ICON_URL>
  urlFrom:
    routeRef:
      name: some-app-route    # This doesn't exist in the namespace
```
Forecastle UI fails to load and shows the following error:
```Results couldn't be loaded due to an error```

Error from the pod:
```error msg="An error occurred while looking for forceastle CRD apps: routes.route.openshift.io \"some-app-route\" not found" _source="filename/filename.go:22"```

**Expected Behavior:**
If the route doesn't exist. Throw an error and ignore that particular CR and loads all the other valid CRs.
