### ISSUE TITLE
Helm forecastle 1.0.65 CustomResourceDefinition "forecastleapps.forecastle.stakater.com" is invalid

### ISSUE THREAD

**Issue by alfsch** [stakater/Forecastle#163]
When I apply the helm chart 1.0.65 with CRD on a fresh and empty kubernetes 1.19.11 cluster I get the following errors

```
The CustomResourceDefinition "forecastleapps.forecastle.stakater.com" is invalid: 
* spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root
* spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead
```
I can fix this errors by changing the CRD in the following way:

```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: forecastleapps.forecastle.stakater.com
spec:
  conversion:
    strategy: None
  group: forecastle.stakater.com
  names:
    kind: ForecastleApp
    listKind: ForecastleAppList
    plural: forecastleapps
    singular: forecastleapp
  preserveUnknownFields: false # has to be false, otherwise '* spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead'
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object  # needed, otherwise '* spec.validation.openAPIV3Schema.type: Required value: must not be empty at the root''
        properties:
```

The lines with the comments are my quick workarounds to get things deployed and running.
