### ISSUE TITLE
Namespace "dev" is hardcoded in the rbac CRB

### ISSUE THREAD

**Issue by rasheedamir** [stakater/Forecastle#23]
Its quite misleading with hardcoded namespace name **dev** in the CRB

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: forecastle-cluster-ingress-role-binding
  labels:
    app: forecastle
    group: com.stakater.platform
    provider: stakater
    version: "0.0.17"
    chart: "forecastle-0.0.17"
    release: "RELEASE-NAME"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forecastle-cluster-ingress-role
subjects:
- kind: ServiceAccount
  name: forecastle
  namespace: dev
```

https://github.com/stakater/Forecastle/blob/master/deployments/kubernetes/forecastle.yaml#L98
