### ISSUE TITLE
Regression in helm chart rbac for ForecastleApp

### ISSUE THREAD

**Issue by sastorsl** [stakater/Forecastle#324]
PR #313 introduced a regression where the referenced resource has a small typo, `forcastleapps` vs `forecastleapps` (`for..` vs `fore..`).

This causes Forecastle's service account to be unable to list configured ForecastleApp resources.

A temporary workaround is:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: forecastle-cluster-ingress-role-workaround
rules:
- apiGroups:
  - forecastle.stakater.com
  resources:
  - forecastleapps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: forecastle
  name: forecastle-cluster-ingress-role-binding-workaround
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: forecastle-cluster-ingress-role-workaround
subjects:
- kind: ServiceAccount
  name: forecastle
  namespace: devops
```

Example where listing fails - and configured ForecastleApp does not show up in Forecastle:

```bash
# oc --as=system:serviceaccount:devops:forecastle get forecastleapp -n openshift-console
Error from server (Forbidden): forecastleapps.forecastle.stakater.com is forbidden: User "system:serviceaccount:devops:forecastle" cannot list resource "forecastleapps" in API group "forecastle.stakater.com" in the namespace "openshift-console"
```

After adding the workaround clusterrole and clusterrolebinding we can list, and we see the app in Forecastle.

```bash
$ oc --as=system:serviceaccount:devops:forecastle get forecastleapp -n openshift-console
NAME                AGE
openshift-console   55m
```
