### ISSUE TITLE
forecastle should crash/fail when run into panic 

### ISSUE THREAD

**Issue by 1337andre** [stakater/Forecastle#345]
Hi folks, 

thanks for this project!

For reasons we have a strange ingress deployment, which causes unfavourable behaviour of forcastle. 
In my option, forecastle should crash, when it runs into panic error. Now, it's still running with error logs, but empty page. 

maybe it would be possible to skip strange ingress with some detailed error messages, so that all other valid ingress are still available?

basically it looks like this:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    forecastle.stakater.com/expose: "true"
...
  labels:
    app.kubernetes.io/managed-by: Helm
  name: strange-ingress
  namespace: webcms-red-dev
spec:
  ingressClassName: intern
  rules:
  - host: webcms-red-dev.nomatter.com
    http:
      paths:
      - backend:
          service:
            name: management-server
            port:
              name: corba
        path: /
        pathType: ImplementationSpecific
  tls:
  - {}
```

logs:
```
forecastle-55c7595d9b-k87kq forecastle time="2023-05-11T12:46:55Z" level=info msg="Found ingress with Name 'strange-ingress' in Namespace 'webcms-red-dev'" _source="filename/filename.go:22"
forecastle-55c7595d9b-k87kq forecastle 2023/05/11 12:46:55 http: panic serving 10.4.177.49:53412: runtime error: index out of range [0] with length 0
forecastle-55c7595d9b-k87kq forecastle goroutine 409 [running]:
forecastle-55c7595d9b-k87kq forecastle net/http.(*conn).serve.func1()
forecastle-55c7595d9b-k87kq forecastle 	/usr/local/go/src/net/http/server.go:1850 +0xbf
forecastle-55c7595d9b-k87kq forecastle panic({0x18dbdc0, 0xc000b7e7f8})
forecastle-55c7595d9b-k87kq forecastle 	/usr/local/go/src/runtime/panic.go:890 +0x262
forecastle-55c7595d9b-k87kq forecastle github.com/stakater/Forecastle/v1/pkg/kube/wrappers.(*IngressWrapper).tryGetTLSHost(...)
forecastle-55c7595d9b-k87kq forecastle 	/go/src/github.com/stakater/Forecastle/pkg/kube/wrappers/ingress.go:103
forecastle-55c7595d9b-k87kq forecastle github.com/stakater/Forecastle/v1/pkg/kube/wrappers.(*IngressWrapper).GetURL(0xc0001fed08)
forecastle-55c7595d9b-k87kq forecastle 	/go/src/github.com/stakater/Forecastle/pkg/kube/wrappers/ingress.go:82 +0x279
forecastle-55c7595d9b-k87kq forecastle github.com/stakater/Forecastle/v1/pkg/forecastle/ingressapps.convertIngressesToForecastleApps({0xc0001d7000?, 0x9, 0x1?})
forecastle-55c7595d9b-k87kq forecastle 	/go/src/github.com/stakater/Forecastle/pkg/forecastle/ingressapps/apps.go:70 +0x2a5
forecastle-55c7595d9b-k87kq forecastle github.com/stakater/Forecastle/v1/pkg/forecastle/ingressapps.(*List).Populate(0xc0001ff7b8, {0xc00058fac0?, 0xc0009072f0?, 0x1?})
forecastle-55c7595d9b-k87kq forecastle 	/go/src/github.com/stakater/Forecastle/pkg/forecastle/ingressapps/apps.go:51 +0x279
forecastle-55c7595d9b-k87kq forecastle github.com/stakater/Forecastle/v1/pkg/handlers.AppsHandler({0x1d8aee0, 0xc000824fc0}, 0xc00017c600?)
forecastle-55c7595d9b-k87kq forecastle 	/go/src/github.com/stakater/Forecastle/pkg/handlers/appsHandler.go:54 +0x485
forecastle-55c7595d9b-k87kq forecastle net/http.HandlerFunc.ServeHTTP(0xc00017c500?, {0x1d8aee0?, 0xc000824fc0?}, 0x800?)
forecastle-55c7595d9b-k87kq forecastle 	/usr/local/go/src/net/http/server.go:2109 +0x2f
forecastle-55c7595d9b-k87kq forecastle github.com/gorilla/mux.(*Router).ServeHTTP(0xc000260300, {0x1d8aee0, 0xc000824fc0}, 0xc00017c400)
forecastle-55c7595d9b-k87kq forecastle 	/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
forecastle-55c7595d9b-k87kq forecastle net/http.serverHandler.ServeHTTP({0xc000896ea0?}, {0x1d8aee0, 0xc000824fc0}, 0xc00017c400)
forecastle-55c7595d9b-k87kq forecastle 	/usr/local/go/src/net/http/server.go:2947 +0x30c
forecastle-55c7595d9b-k87kq forecastle net/http.(*conn).serve(0xc000826e60, {0x1d8bab8, 0xc0001ee9c0})
forecastle-55c7595d9b-k87kq forecastle 	/usr/local/go/src/net/http/server.go:1991 +0x607
forecastle-55c7595d9b-k87kq forecastle created by net/http.(*Server).Serve
forecastle-55c7595d9b-k87kq forecastle 	/usr/local/go/src/net/http/server.go:3102 +0x4db
```

image/version: stakater/forecastle:v1.0.125
