### ISSUE TITLE
[BUG] Icons don't get displayed

### ISSUE THREAD

**Issue by lachnerd** [stakater/Forecastle#412]
**Describe the bug**

CSS of every app element truns into this:

```
<div class="MuiCardMedia-root jss18" title="kroki" style="background-image: url(&quot;`https://github.com/walkxcode/dashboard-icons/blob/main/png/alpine.png`&quot;);"></div>
```

Theres &quot; added at the beginning and the end of the image url with leads to the icon image beeing not rendered on the page

**To Reproduce**
just add an icon

**Expected behavior**
Icon gets displayed

**Screenshots**
<img width="730" alt="image" src="https://github.com/stakater/Forecastle/assets/25339466/11c7b730-b831-43c3-909a-f43c60e8a91c">

**Environment**
 - Kubernetes Version: v1.27.7

**Comment by MuneebAijaz** [comment]
@lachnerd can you pls share the version you are using and the manifests you are applying? we will try to reproduce the issue

**Comment by lachnerd** [comment]
Hi,
i'm now using stakater/forecastle:v1.0.134 with the helm chart.

I added forecastle config as ingress annotations:

```
ingress:
  enabled: true
  hostname: keycloak.domain.tld
  ingressClassName: internal-global
  annotations: 
    forecastle.stakater.com/expose: 'true'
    forecastle.stakater.com/icon: 'https://github.com/stakater/ForecastleIcons/blob/master/keycloak.png'
    forecastle.stakater.com/group: 'Tools'
```

which leads to :

```
<button class="MuiButtonBase-root MuiCardActionArea-root" tabindex="0" type="button"><div class="MuiGrid-root jss17"><div class="MuiCardMedia-root jss18" title="keycloak" style="background-image: url(&quot;https://github.com/stakater/ForecastleIcons/blob/master/keycloak.png&quot;);"></div></div><span class="MuiCardActionArea-focusHighlight"></span><span class="MuiTouchRipple-root"></span></button>
```
